import unittest
import numpy as np
from utils.scale import MinMaxScaler, RobustScaler, StandardScaler

class TestMinMaxScaler(unittest.TestCase):...
class TestRobustScaler(unittest.TestCase):...
class TestStandardScaler(unittest.TestCase):...